const cors = require("cors");
const express = require("express");

const stripe = require("stripe")("sk_test_51IeHKMSIiEuztJl8IZRBKxHVXMKwfhfjdiIH7BQKTTce38E39XA0kkk0L1iWxZMVtN6b4zWQDGUAh9ivYLHv76wT0090v9lTp8"); //stripe key!
const uuid = require("uuid");

const app = express();

//middlewares
app.use(express.json());
app.use(cors());


//routes
app.get("/", (req,res) => {
    res.send("Working!!!")
});

app.post("/payment" , (req, res) => {
    const {product, token} = req.body;
    console.log("Product :", product);
    console.log("Price :", product.price);
    const idempontencyKey = uuid();   //idempotency key is a unique value generated by the client which the server uses to recognize subsequent retries of the same request. 

    return stripe.customers.create({
        email: token.email,
        source: token.id
    })
    .then (customer => {
        stripe.charges.create({
            amount: product.price * 100,
            currency: 'usd',
            customer:customer.id,
            receipt_email: token.email,
            description: `Your Product is ${product.name}`,
            shipping: {
                name: token.card.name,
                address: {
                    country: token.card.address_country
                }
            }
        },
        {idempontencyKey}
        );
    })
    .then(result => res.status(200).json(result))
    .catch(err => console.log(err))
})


//listen
app.listen(3040, () => console.log("Running on port 3040"));